# use vnc full image
image: gitpod/workspace-full-vnc

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: install Firefox
    init: sudo apt update && sudo apt upgrade -y && sudo apt install firefox -y && clear && echo "Firefox Is Installed." # runs during prebuild
  - name: install Eclipse
    init: |
      mkdir -p /home/gitpod/Downloads &&
      curl https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/integration/12.0.2.0-ACE-LINUX64-DEVELOPER.tar.gz -o /home/gitpod/Downloads/eai.tar.gz &&
      tar -xvzf /home/gitpod/Downloads/eai.tar.gz -C /home/gitpod/Downloads
      #      curl -L https://www.mirrorservice.org/sites/download.eclipse.org/eclipseMirror/technology/epp/downloads/release/2022-09/R/eclipse-java-2022-09-R-linux-gtk-x86_64.tar.gz -o /home/gitpod/Downloads/eclipse.tar.gz &&
      #      tar -xvzf /home/gitpod/Downloads/eclipse.tar.gz -C /home/gitpod/Downloads &&
      gp sync-done inst
  - name: Start Eclipse
    command: |
      gp sync-await inst &&
      /home/gitpod/Downloads/eclipse/eclipse
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 6080
    onOpen: open-browser
  - port: 5900
    onOpen: ignore
    